#!/usr/bin/env python
#
#  Copyright 2014 The BCE Authors. All rights reserved.
#  Use of this source code is governed by a BSD-style license that can be
#  found in the license.txt file.
#

PE_MEXP_UNRECOGNIZED_TOKEN = 110
PE_MEXP_DUPLICATED_DECIMAL_DOT = 111
PE_MEXP_USE_PROTECTED_SYMBOL_HEADER = 112
PE_MEXP_MISSING_OPERAND = 113
PE_MEXP_MISSING_OPERATOR = 114
PE_MEXP_FN_UNSUPPORTED = 115
PE_MEXP_FN_ARGC_MISMATCH = 116
PE_MEXP_NO_CONTENT = 117
PE_MEXP_PARENTHESIS_MISMATCH = 118
PE_MEXP_ILLEGAL_ARG_SEPARATOR = 119
PE_MEXP_RPNEV_DIVIDE_ZERO = 120
PE_MEXP_RPNEV_SQRT_NEG_ARG = 121