#!/usr/bin/env python
#
#  Copyright 2014 - 2015 The BCE Authors. All rights reserved.
#  Use of this source code is governed by a BSD-style license that can be
#  found in the license.txt file.
#

PE_MEXP_UNRECOGNIZED_TOKEN = 100
PE_MEXP_DUPLICATED_DECIMAL_DOT = 101
PE_MEXP_USE_PROTECTED_SYMBOL_HEADER = 102
PE_MEXP_MISSING_OPERAND = 103
PE_MEXP_MISSING_OPERATOR = 104
PE_MEXP_FN_UNSUPPORTED = 105
PE_MEXP_FN_ARGC_MISMATCH = 106
PE_MEXP_NO_CONTENT = 107
PE_MEXP_PARENTHESIS_MISMATCH = 108
PE_MEXP_ILLEGAL_ARG_SEPARATOR = 109
PE_MEXP_RPNEV_DIVIDE_ZERO = 110
PE_MEXP_RPNEV_SQRT_NEG_ARG = 111