#!/usr/bin/env python
#
#  Copyright 2014 - 2015 The BCE Authors. All rights reserved.
#  Use of this source code is governed by a BSD-style license that can be
#  found in the license.txt file.
#

PE_MEXP_UNRECOGNIZED_TOKEN = "PE.MEXP.URTK"
PE_MEXP_DUPLICATED_DECIMAL_DOT = "PE.MEXP.DPDT"
PE_MEXP_USE_PROTECTED_SYMBOL_HEADER = "PE.MEXP.UPSH"
PE_MEXP_MISSING_OPERAND = "PE.MEXP.MSOPD"
PE_MEXP_MISSING_OPERATOR = "PE.MEXP.MSOPR"
PE_MEXP_FN_UNSUPPORTED = "PE.MEXP.USFN"
PE_MEXP_FN_ARGC_MISMATCH = "PE.MEXP.MSAC"
PE_MEXP_NO_CONTENT = "PE.MEXP.NCNT"
PE_MEXP_PARENTHESIS_MISMATCH = "PE.MEXP.PMC"
PE_MEXP_ILLEGAL_ARG_SEPARATOR = "PE.MEXP.ILAS"
PE_MEXP_RPNEV_DIVIDE_ZERO = "PE.MEXP.DVZ"
PE_MEXP_RPNEV_SQRT_NEG_ARG = "PE.MEXP.SQN"